# Basic
title: 狷墨居
subtitle: 狷墨居主人的个人天地
welcome_message: <a href="https://github.com/linusboyle/linusboyle.github.io" target="_blank">本站源码</a>
description: 记录狷墨居主人的技术心得、生活点滴
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
#nav:
    #- {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 5370899507
    github: linusboyle
    #twitter: onevcat
    #facebook: boyle.linus.5
    gplus: 106875862514148562818
    mail: hzl17@mails.tsinghua.edu.cn

# Google Analytics
#ga:
    # id: your_ga_id
    # host: your_host
