# Basic 

markdown: rdiscount #kramdown
title: DA1SY
subtitle: 偏有宸机
#welcome_message: 诗词爱好者，艺术爱好者，渗透测试工程师，Python爱好者，小姐姐爱好者，在校高中生。
description: 天下惟庸人无谤无誉
#description: 不恨古人吾不见，恨古人不见吾狂耳
creator: <a href="https://github.com/da1sy">@DA1SY</a>

url: "https://da1sy.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: 博客

# Navigation buttons in the front page.
nav:
    #- {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    - {title: Tags, description: 文章分类, url: '/tags'}
    - {title: Qzone, description: QQ空间, url: 'https://user.qzone.qq.com/3078187521'}
    - {title: Me, description: 关于我, url: 'https://da1sy.github.io/9999/09/About-Me'}
    #- {title: The archive, description: 文章归档, url: '/archives'}
    
# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
#comment:
    #disqus: vno-jekyll
    # duoshuo: 
comment:
    gitalk:
        enable: true #是否开启
        ClientID: e9fcef3c7903a8c4a875
        ClientSecret: 8cedc80efacb5ba48c917ea59491a1deee26a714
        #repo: da1sy.github.io
        repo: https://github.com/da1sy/da1sy-PL
        adminUser: da1sy # 评论初始化账户(GitHub ID)
        owner: da1sy
        

# Social
social:
    weibo: 6300341967
    github: da1sy
    #twitter: onevcat
    #facebook: boyle.linus.5
    #gplus: 106875862514148562818
    mail: oneda1sy@outlook.com
    QQ: 3078187521

# Google Analytics
ga:
     id: UA-121698925-1
     host: da1sy.github.io
# Show PV/UV of the website/page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi/
busuanzi_count:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i> 访问人数
  site_uv_footer: 人
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i> 总访问量
  site_pv_footer: 次
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"></i> 阅读数
  page_pv_footer:
